import Head from 'next/head'
import Header from '../components/Header'
import PostSection from '../components/PostSection'
import SideBar from '../components/SideBar'
import TimeLine from '../components/TimeLine'

export default function Home() {
  return (
    <div className='bg-[#f3f2ef] dark:bg-black dark:text-white h-screen overflow-y-hidden md:space-y-6'>
      <Head>
        <title>Meet | Chat, Make Friend from around the world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <Header />
      <section className='grid mx-auto mt-3 gap-3 grid-cols-9'>
        {/* sidebar */}
        <SideBar />
         {/*post */}
         <PostSection />
          {/* tweet */}
          <TimeLine />
      </section>
     </main>
    </div>
  )
}
